// COLORS
var SELECTED = "#69ACAB";

var leftSVGDataOptions = [
    "Population",
    "Pop. % Change (10 yrs)",
    "Pop. per Square Mile",
    "Land Area (sq. mi.)",
    "% Pop. Under 5",
    "% Pop. Under 18",
    "% Pop. Over 65",
    "% Female",
    "% American Indian",
    "% Asian American",
    "% African American",
    "% Hispanic",
    "% Caucasian",
    "% Foreign Born",
    "Number of Veterans",
    "Median Gross Rent",
    "Number of Households",
    "Persons per Household",
    "Avg. Commute Time",
    "Median Household Income",
    "Per Capita Income",
    "% In Poverty",
    "Total Employment",
    "% w/ High School Degree",
    "% w/ Bachelor's Degree",
    "Persons w/o Health Insurance",
    "a",
    "a",
    "a",
    "a",
    "a",
    "a",
]

