var leftSVGDataOptions = [
    "Population",
    "Pop. % Change (10 yrs)",
    "Population per Square Mile",
    "Land Area (sq. mi.)",
    "% Pop. Under 5",
    "% Pop. Under 18",
    "% Pop. Over 65",
    "% Female",
    "% American Indian",
    "% Asian American",
    "% African American",
    "% Hispanic",
    "% White",
    "Number of Veterans",
    "Median Gross Rent",
    "Number of Households",
    "Persons per Household",
    "Avg. Commute Time",
    "Median Household Income",
    "% In Poverty",
    "Total Employment",
    "% w/ High School Degree",
    "% w/ Bachelor's Degree",
    "Persons w/o Insurance",
    "a",
    "a",
    "a",
    "a",
    "a",
    "a",
    "a",
    "a",
    "a",
    "a",
    "a",
    "a",
    "a",
    "a",
    "a",
    "a",
    "a",
    "a",
    "a",
]

svgRects = [];