// Store large data structures and other miscellaneous information that does not change.

var attributesToCSV = {
    "!POPULATION STATISTICS": null,
    "Total Population": "Population estimates, July 1, 2019,  (V2019)",
    "Population % Change (10 yrs)": "Population, percent change - April 1, 2010 (estimates base) to July 1, 2019,  (V2019)",
    "Population per Square Mile": "Population per square mile, 2010",
    "!DEMOGRAPHICS": null,
    "% Foreign Born": "Foreign born persons, percent, 2014-2018",
    "% African American": "Black or African American alone, percent",
    "% American Indian": "American Indian and Alaska Native alone, percent",
    "% Asian American": "Asian alone, percent",
    "% Caucasian": "White alone, percent",
    "% Hispanic": "Hispanic or Latino, percent",
    "% Female": "Female persons, percent",
    "% of Pop. Under 5": "Persons under 5 years, percent",
    "% of Pop. Under 18": "Persons under 18 years, percent",
    "% of Pop. 65 And Over": "Persons 65 years and over, percent",
    "!SOCIOECONOMIC FACTORS": null,
    "Persons per Household": "Persons per household, 2014-2018",
    "Median Household Income": "Median household income (in 2018 dollars), 2014-2018",
    "Income Per Capita": "Per capita income in past 12 months (in 2018 dollars), 2014-2018",
    "Median Gross Rent": "Median gross rent, 2014-2018",
    "% In Poverty": "Persons in poverty, percent",
    "Total Employment": "Total employment, 2018",
    "Total Employment % Change (1 yr)": "Total employment, percent change, 2017-2018",
    "!MISCELLANEOUS": null,
    "% w/ High School Degree": "High school graduate or higher, percent of persons age 25 years+, 2014-2018",
    "% w/ Bachelor's Degree": "Bachelor's degree or higher, percent of persons age 25 years+, 2014-2018",
}

var polygonPosRegular = [
    [365, 325],
    [712, 327],
    [347, 239],
    [607, 213],
    [655, 250],
    [424, 260],
    [725, 267],
    [653, 284],
    [488, 305],
    [350, 282],
    [438, 281],
    [554, 333],
    [480, 233],
    [249, 314],
    [722, 62],
    [704, 374],
    [663, 74],
    [654, 229],
    [671, 321],
    [656, 173],
    [515, 137],
    [386, 272],
    [390, 218],
    [716, 475],
    [303, 219],
    [660, 409],
    [349, 212],
    [508, 197],
    [695, 482],
    [686, 439],
    [593, 65],
    [681, 262],
    [462, 266],
    [503, 333],
    [443, 218],
    [563, 308],
    [720, 123],
    [562, 150],
    [572, 225],
    [606, 274],
    [702, 245],
    [424, 323],
    [703, 180],
    [695, 278],
    [462, 336],
    [520, 288],
    [595, 330],
    [293, 264],
    [688, 488],
    [532, 232],
    [526, 230],
    [715, 405],
    [673, 497],
    [460, 305],
    [616, 384],
    [677, 365],
    [737, 190],
    [305, 320],
];

var polygonPosWeird = [
    [795, 457],
    [699, 469],
    [688, 478],
    [708, 447],
];

var countyCSVInfo = {
	'Albany': {}, 'Allegany': {}, 'Bronx': {}, 'Broome': {}, 'Cattaraugus': {}, 'Cayuga': {},
	'Chautauqua': {}, 'Chemung': {}, 'Chenango': {}, 'Clinton': {}, 'Columbia': {}, 'Cortland': {},
	'Delaware': {}, 'Dutchess': {}, 'Erie': {}, 'Essex': {}, 'Franklin': {}, 'Fulton': {},
	'Genesee': {}, 'Greene': {}, 'Hamilton': {}, 'Herkimer': {}, 'Jefferson': {}, 'Kings': {},
	'Lewis': {}, 'Livingston': {}, 'Madison': {}, 'Monroe': {}, 'Montgomery': {}, 'Nassau': {},
	'New York': {}, 'Niagara': {}, 'Oneida': {}, 'Onondaga': {}, 'Ontario': {}, 'Orange': {},
	'Orleans': {}, 'Oswego': {}, 'Otsego': {}, 'Putnam': {}, 'Queens': {}, 'Rensselaer': {},
	'Richmond': {}, 'Rockland': {}, 'Saratoga': {}, 'Schenectady': {}, 'Schoharie': {}, 'Schuyler': {},
	'Seneca': {}, 'St. Lawrence': {}, 'Steuben': {}, 'Suffolk': {}, 'Sullivan': {}, 'Tioga': {},
	'Tompkins': {}, 'Ulster': {}, 'Warren': {}, 'Washington': {}, 'Wayne': {}, 'Westchester': {},
	'Wyoming': {}, 'Yates': {}, 'New York State': {}
};

var countyPopulationEstimates = {
    'Albany': {}, 'Allegany': {}, 'Bronx': {}, 'Broome': {}, 'Cattaraugus': {}, 'Cayuga': {},
	'Chautauqua': {}, 'Chemung': {}, 'Chenango': {}, 'Clinton': {}, 'Columbia': {}, 'Cortland': {},
	'Delaware': {}, 'Dutchess': {}, 'Erie': {}, 'Essex': {}, 'Franklin': {}, 'Fulton': {},
	'Genesee': {}, 'Greene': {}, 'Hamilton': {}, 'Herkimer': {}, 'Jefferson': {}, 'Kings': {},
	'Lewis': {}, 'Livingston': {}, 'Madison': {}, 'Monroe': {}, 'Montgomery': {}, 'Nassau': {},
	'New York': {}, 'Niagara': {}, 'Oneida': {}, 'Onondaga': {}, 'Ontario': {}, 'Orange': {},
	'Orleans': {}, 'Oswego': {}, 'Otsego': {}, 'Putnam': {}, 'Queens': {}, 'Rensselaer': {},
	'Richmond': {}, 'Rockland': {}, 'Saratoga': {}, 'Schenectady': {}, 'Schoharie': {}, 'Schuyler': {},
	'Seneca': {}, 'St. Lawrence': {}, 'Steuben': {}, 'Suffolk': {}, 'Sullivan': {}, 'Tioga': {},
	'Tompkins': {}, 'Ulster': {}, 'Warren': {}, 'Washington': {}, 'Wayne': {}, 'Westchester': {},
	'Wyoming': {}, 'Yates': {}, 'New York State': {}
}

var searchResultCountyNames = [];
